steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck-services/activity:latest', '-f', 'apps/activity/Dockerfile', '.']
images:
- 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck-services/activity:latest'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
