steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'APP_NAME=api', '-t', 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/api:latest', '.']
images:
- 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/api:latest'
options:
  logging: CLOUD_LOGGING_ONLY
