steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
    - 'build'
    - '--build-arg'
    - 'APP_NAME=${_SERVICE_NAME}'
    - '-t'
    - 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    - '-f'
    - 'apps/${_SERVICE_NAME}/Dockerfile'
    - '.'

# Automate Cloud Run Deployment
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - '${_SERVICE_NAME}'
    - '--image'
    - 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'
    - '--region'
    - '${_REGION}'
    - '--allow-unauthenticated'

images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: 'api' # Default service
  _REPOSITORY: 'tiltcheck-services'
  _REGION: 'us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
