steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'APP_NAME=discord-bot', '-t', 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/discord-bot:latest', '.']
images:
- 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/discord-bot:latest'
options:
  logging: CLOUD_LOGGING_ONLY`n  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
