steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/trust-rollup:latest', '-f', 'apps/trust-rollup/Dockerfile', '.']
images:
- 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/trust-rollup:latest'
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

