steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/control-room:latest', '-f', 'apps/control-room/Dockerfile', '.']
images:
- 'us-central1-docker.pkg.dev/tiltchcek/tiltcheck/control-room:latest'
options:
  logging: CLOUD_LOGGING_ONLY`n  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
