
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY .npmrc ./

RUN npm install -g pnpm
RUN pnpm install

COPY . .

RUN pnpm --filter @tiltcheck/api build

EXPOSE 3001

CMD [ "pnpm", "--filter", "@tiltcheck/api", "start" ]
