packages:
  - apps/*
  - modules/*
  - packages/*

ignoredBuiltDependencies:
  - puppeteer
  - '@gsknnft/bigint-buffer'

onlyBuiltDependencies:
  - esbuild
  - pg
  - bcryptjs
  - sharp
  - scrypt-kdf
