-- Fix missing tables for JustTheTip and LockVault
-- Run this in Supabase SQL Editor to fix "Could not find table" errors

-- 1. Wallet Registrations (Required for JustTheTip)
CREATE TABLE IF NOT EXISTS wallet_registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL, -- Discord ID
  wallet_address TEXT NOT NULL,
  label TEXT,
  is_primary BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_wallet_registrations_user_id ON wallet_registrations(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_registrations_wallet_address ON wallet_registrations(wallet_address);

-- 2. Vault Transactions (Required for LockVault)
CREATE TABLE IF NOT EXISTS vault_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  amount_sol NUMERIC,
  transaction_type TEXT, -- 'lock', 'unlock', 'auto'
  tx_signature TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);