-- © 2024–2026 TiltCheck Ecosystem. All Rights Reserved. Last Updated: 2026-04-09
-- Migration 006: collab_applications table
-- Run in Supabase SQL Editor

CREATE TABLE IF NOT EXISTS collab_applications (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email           TEXT NOT NULL,
  name            TEXT NOT NULL,
  organization    TEXT,
  collab_type     TEXT NOT NULL,
  description     TEXT NOT NULL,
  website         TEXT,
  discord_username TEXT,
  referral_source TEXT DEFAULT 'direct',
  status          TEXT NOT NULL DEFAULT 'pending', -- pending | approved | rejected | archived
  reviewed_by     TEXT,                             -- admin Discord ID
  reviewed_at     TIMESTAMPTZ,
  notes           TEXT,                             -- internal review notes
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_collab_applications_email
  ON collab_applications(email);

CREATE INDEX IF NOT EXISTS idx_collab_applications_status
  ON collab_applications(status);

CREATE INDEX IF NOT EXISTS idx_collab_applications_collab_type
  ON collab_applications(collab_type);

COMMENT ON TABLE collab_applications IS
  'Partner, integration, and collab applications submitted via tiltcheck.me/collab. Notifications route to BETA_APPLICATIONS Discord channel.';
