/* Copyright (c) 2026 TiltCheck Ecosystem. All Rights Reserved. */
/**
 * Daily Task AI Agent
 * 
 * Aggregates local context (TODO, Logs, Intel) and uses Ollama to suggest 
 * a prioritized daily task list. Handles brand-specific requests like 
 * "grant opportunities" and "email cleanup".
 */

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

// --- CONFIGURATION ---
const OLLAMA_URL = process.env.OLLAMA_URL || 'http://localhost:11434/v1';
const AI_MODEL = process.env.AI_MODEL || 'llama3.2:1b';
const TODO_PATH = path.resolve(process.cwd(), 'TODO.md');
const LOG_PATH = path.resolve(process.cwd(), 'SESSION_LOG.md');
const INTEL_PATH = path.resolve(process.cwd(), 'data/degen-intel-events.jsonl');
const TASK_OUTPUT_PATH = path.resolve(process.cwd(), 'docs/ops/daily-tasks-ai.md');

// --- CACHED GRANT INTEL (Seeded 2026-03-24) ---
const GRANT_INTEL = [
  {
    name: "Solana Foundation Public Goods Grant",
    focus: "Open source, network security, developer tools",
    status: "Rolling applications",
    relevance: "High for TiltCheck protocols (Solana Vaults)"
  },
  {
    name: "Solana Mobile Colosseum Hackathon",
    focus: "Mobile-first crypto apps",
    timing: "Anticipated Q1 2026",
    relevance: "High for Chrome Extension port to Mobile"
  },
  {
    name: "NCPG Agility Grants (Responsible Gambling)",
    focus: "Prevention strategies, problem gambling initiatives",
    timing: "Spring 2026 period closed, look for Fall/Winter 2026 cycles",
    relevance: "Primary alignment for RGaaS"
  },
  {
    name: "Colorado Responsible Gaming Grant Program",
    focus: "Responsible gaming innovation",
    timing: "Next cycle approvals: February 2026 (Verify next one)",
    relevance: "Regulatory alignment"
  }
];

async function main() {
  console.log('\x1b[32m%s\x1b[0m', '=== TiltCheck Daily Task AI Agent ===');
  
  // 1. Load context
  const todoContent = loadFile(TODO_PATH);
  const logContent = loadFile(LOG_PATH);
  const intelContent = loadRecentIntel(INTEL_PATH, 5);

  console.log('[INFO] Context loaded.');

  // 2. Prepare System Prompt
  const SYSTEM_PROMPT = `You are TiltCheck's Chief Operations Agent.
Your goal is to provide a daily task list for the developer.
Tone: Blunt, clinical, degen-centric. No fluff. No emojis.
Context: 
- Current TODO list
- Recent session history
- Recent email/intel ingest
- Current Grant Opportunities

Strategy:
- Prioritize tasks that "secure the bag" or "harden the protocol".
- Include a section for "Grant Opportunities" based on the provided intel.
- Include an "Email Clean Up" task if the intel shows high volume.
- Output in Markdown format.`;

  const USER_PROMPT = `Generate a daily task list for 2026-03-24.

TODO Context:
${todoContent.slice(0, 500)}

Recent History:
${logContent.slice(0, 500)}

Recent Intel:
${intelContent}

Grant Intel:
${JSON.stringify(GRANT_INTEL, null, 2)}`;

  // 3. Call Ollama
  console.log(`[INFO] Querying Ollama (${AI_MODEL})...`);
  try {
    const response = await fetch(`${OLLAMA_URL}/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        model: AI_MODEL,
        messages: [
          { role: 'system', content: SYSTEM_PROMPT },
          { role: 'user', content: USER_PROMPT }
        ],
        temperature: 0.7
      })
    });

    if (!response.ok) {
        if (response.status === 404 || response.status === 500) {
            console.error('\x1b[31m%s\x1b[0m', '[ERROR] Ollama server not responding correctly. Is it running?');
            process.exit(1);
        }
        throw new Error(`Ollama API error: ${response.statusText}`);
    }

    const data = await response.json();
    const taskList = data.choices[0].message.content;

    // 4. Output and Save
    const header = `# Daily Tasks - 2026-03-24 (AI Suggested)\n\n*Generated by TiltCheck Task AI*\n\n`;
    const finalContent = header + taskList + `\n\n---\n*Made for Degens. By Degens.*`;

    if (!fs.existsSync(path.dirname(TASK_OUTPUT_PATH))) {
      fs.mkdirSync(path.dirname(TASK_OUTPUT_PATH), { recursive: true });
    }
    fs.writeFileSync(TASK_OUTPUT_PATH, finalContent);

    console.log('\x1b[32m%s\x1b[0m', '[SUCCESS] Daily task list generated: docs/ops/daily-tasks-ai.md');
    console.log('\n' + finalContent);

  } catch (error) {
    console.error('\x1b[31m%s\x1b[0m', '[ERROR] Failed to generate task list.');
    console.error(error.message);
    
    // Provide a fallback if Ollama fails
    console.log('\n[FALLBACK] Suggesting basic tasks based on context:');
    console.log('1. Review TODO.md and SESSION_LOG.md');
    console.log('2. Check Solana Foundation Grant RFPs (rolling)');
    console.log('3. Clean up ingested casino emails in scripts/gmail-ingest.mjs output');
    console.log('4. Run daily-ops.ps1 to sync branches');
  }
}

function loadFile(filePath) {
  try {
    if (!fs.existsSync(filePath)) return '(No file found)';
    return fs.readFileSync(filePath, 'utf8');
  } catch (err) {
    return '(Error reading file)';
  }
}

function loadRecentIntel(filePath, count) {
  try {
    if (!fs.existsSync(filePath)) return '(No intel found)';
    const lines = fs.readFileSync(filePath, 'utf8').trim().split('\n');
    return lines.slice(-count).join('\n');
  } catch (err) {
    return '(Error reading intel)';
  }
}

main().catch(console.error);
